# frozen_string_literal: true

source 'https://rubygems.org'

gem 'bootsnap', require: false
gem 'concurrent-ruby', '~> 1.3'
gem 'gte', path: '/gte'
gem 'numo-narray', '~> 0.9'
gem 'onnxruntime', '~> 0.9'
gem 'puma', '~> 6.4'
gem 'rails', '~> 7.1'
gem 'tokenizers', '~> 0.5'
