source "https://rubygems.org"

gem "rails", "~> 7.1"
gem "puma", "~> 6.4"
gem "gte", path: "/gte"
gem "onnxruntime", "~> 0.9"
gem "tokenizers", "~> 0.5"
gem "numo-narray", "~> 0.9"
gem "concurrent-ruby", "~> 1.3"
gem "bootsnap", require: false
